#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCVEzpECj2QfsR4Cuj5U51tSL+OkUx79NGm
P7geqL8vZiiJJVnGa0hrK4NyJUNnRVgu8IwS7OkLQtD1QBb/4+53O8eayKNhjiYs
ABxJ+siMSWz1gNET7SHwTOzQ0fElseJQQCMIB+WT4dSqwuyIh6bkyYvkJOIaTD3n
Cbzsm9qDjFfsWAQ6BmY2eRpSj0n8olH8/w3I8UgkyuM89C5CCBuI6i3x7B7RV5qf
3fEaWJS5X0Xfz6HFVlCXyZQ9PO9mjv+Crf7eZDOs0XYWteVbIJ6BlFYelHoD2GW0
e+ZXddCWWVzYIbxTR6Mjpe9AELk/8Mpp3d0cIn2oF4r1UzTB13h/ aws-key       
ssh_pwauth: false
disable_root: false 
package_update: true
packages:
  - curl 
  - wget 
