#cloud-config

# Benutzerkonfiguration
users:
  - name: ubuntu                     # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL     # Berechtigung, sudo ohne Passwort einzusetzen
    groups: users, admin             # Gruppenzugehörigkeit
    home: /home/ubuntu               # Heimatverzeichnis
    shell: /bin/bash                 # Standard-Shell
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: false  # Deaktiviert SSH-Passwortauthentifizierung
disable_root: false  # Erlaubt die Verwendung des Root-Benutzers
package_update: true  # Aktualisiert das Paketrepository
packages:
  - curl  # Installiert das Paket "curl"
  - wget  # Installiert das Paket "wget"
