#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCP5v1Q6JsOg9SnibCpIA+6la/eZueMizy44DhiIrPKCHeVHdS4u++wTQTKR23X3bawSZggslcKmj+2V9XCnxt+mCOIu8tlN56w9Uj3Og3KQBiCDvnSwexgDuD/5/j1S7w+T7kyr0RmZYcXFW5458wIy9PHIFgd/dlmt6uJCbjWsDfGgYyyPwpKQYl0pYKaKBs3WDsjLq6wWHZwRd/IZ2t8FvhY2nIQqOCxymmlLIgfMOfOLYDo/C78alYde3nO3aEXWlTsc8HrYyA5gL+g6skNcsv7uz0ROsj5Fhw/P+ytQXTr7asqAhHZ2R7Fg4Drc4zd5iXeZo4plaTGIBhFzE4n aws-key
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCLEuXwRbTzsqDElJvbZqIGhJ1swPBj71hEiATCyFjD9iw6LdR1bHBjWM3XOyX8+TqIJDOSrvN75CY8w9DJnVlPA1u4byOPSXNzYrInJ1WSqxwvdCF3QB2H3MlEFO2b6JsreTjuzFjKxUucVSvEMw8t3YcA0SHcNCfiywSB0dldoYmoylOMP6QhYInm1m3HLEdVveKLqQQl9XJhK2UwgcZZQdtW9wzL+8Axwe9nmGJxiHFHZwKdvxbsK8BbXQNIafqReGafSqlSloy04CZgIzJ35fUjb+d6WxqfEkJzPCxy24Rrh/m+PueMyJSGW+3hf9KtzDGPtxOZiRFC3+pkNR4L aws-key
ssh_pwauth: false
disable_root: false 
package_update: true
packages:
  - curl 
  - wget 
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer

write_files:
  - path: /var/www/html/db.php
    content: |
      <?php
              //database
              $servername = "172.31.32.116";
              $username = "admin";
              $password = "password";
              $dbname = "mysql";

              // Create connection
              $conn = new mysqli($servername, $username, $password, $dbname);
              // Check connection
              if ($conn->connect_error) {
                      die("Connection failed: " . $conn->connect_error);
              }

              $sql = "select Host, User from mysql.user;";
              $result = $conn->query($sql);
              while($row = $result->fetch_assoc()){
                      echo($row["Host"] . " / " . $row["User"] . "<br />");
              }
              //var_dump($result);
      ?>
  - path: /var/www/html/info.php
    content: |
      <?php
      // Show all information, defaults to INFO_ALL
      phpinfo();
      ?>

runcmd:
  - a2enconf adminer
  - systemctl restart apache2